///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String cameraAdd = 'lib/assets/svg/camera-add.svg';
  static const String carrinhoCompras = 'lib/assets/svg/carrinho-compras.svg';
  static const String freezer = 'lib/assets/svg/freezer.svg';
  static const String produtos = 'lib/assets/svg/produtos.svg';
  static const String receitas = 'lib/assets/svg/receitas.svg';
  static const String sugestaoCompras = 'lib/assets/svg/sugestao-compras.svg';

}
